baseURL: "https://shimmering-figolla-4e124d.netlify.app/"
languageCode: 'en-us'
title: 'Sacred Space in South Asia'
author:
  name: '[your name(s) here]'

Params:
  background: ""
  surface: ""
  text: ""
