languageCode: en-us
title: Sacred Space in South Asia
baseURL: https://cozy-meerkat-3a32bd.netlify.app/
author:
  name: Bobby Grygiel
Params:
  background: "#9174ec"
  surface: ""
  primary: ""
  secondary: ""
  accent: ""
  mapStyle: https://tile.openstreetmap.org/{z}/{x}/{y}.png
