languageCode: en-us
title: Sacred Space in South Asia
baseURL: https://dulcet-empanada-17b947.netlify.app
author:
  name: Bobby Grygiel
Params:
  background: "#9174ec"
  surface: ""
  primary: ""
  secondary: ""
  accent: ""
  mapStyle: https://tile.openstreetmap.org/{z}/{x}/{y}.png
