languageCode: en-us
title: Sacred Space in South Asia
baseURL: https://633f2f3fb4df220009f3b0cd--cozy-meerkat-3a32bd.netlify.app/
author:
  name: Jameson Mannix
Params:
  background: ""
  surface: ""
  primary: ""
  secondary: ""
  accent: ""
  mapStyle: https://tile.openstreetmap.org/{z}/{x}/{y}.png
