languageCode: en-us
title: Sacred Space in South Asia
baseURL: https://dulcet-empanada.app
author:
  name: Bobby Grygiel
Params:
  background: ""
  surface: ""
  primary: ""
  secondary: ""
  accent: ""
  mapStyle: https://tile.openstreetmap.org/{z}/{x}/{y}.png
