languageCode: 'en-us'
title: 'Sacred Space in South Asia'
baseURL: "https://shimmering-figolla-4e124d.netlify.app/"
author:
  name: '[your name(s) here]'

Params:
  background: ""
  surface: ""
  primary: ""
  secondary: ""
  accent: ""
