backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/img"
public_folder: "/img"
collections:
  - name: 'config'
    label: 'Configuration'
    files:
      - name: 'config'
        label: 'Configuration'
        file: 'config.yaml'
        fields:
          - label: 'Site Title'
            name: 'title'
            widget: 'string'
          - label: 'Web Address'
            name: 'baseURL'
            widget: 'string'
            hint: "your site's URL as given by Netlify"
          - label: 'Name'
            name: 'author'
            widget: 'object'
            fields:
              - { label: 'Name', name: 'name', widget: 'string'}
          - label: 'Styles'
            name: 'Params'
            widget: 'object'
            fields:
              - { label: 'Background Color', name: 'background', widget: 'color', required: false }
              - { label: 'Surface Color', name: 'surface', widget: 'color', required: false }
              - { label: 'Primary Color', name: 'primary', widget: 'color', required: false }
              - { label: 'Secondary Color', name: 'secondary', widget: 'color', required: false }
              - { label: 'Accent Color', name: 'accent', widget: 'color', required: false }
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/_index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Featured Image', name: 'image', widget: 'image' }
          - { label: 'Image Caption', name: 'caption', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: 'overview'
        label: 'Overview'
        file: 'content/overview.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Featured Image', name: 'image', widget: 'image' }
          - { label: 'Image Caption', name: 'caption', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {label: "Location", name: "location", widget: "map", type: "Polygon", required: false }
      - name: 'history'
        label: 'History'
        file: 'content/history.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Featured Image', name: 'image', widget: 'image' }
          - { label: 'Image Caption', name: 'caption', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {label: "Location", name: "location", widget: "map", type: "Polygon", required: false }
      - name: 'practice'
        label: 'Practice'
        file: 'content/practice.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Featured Image', name: 'image', widget: 'image' }
          - { label: 'Image Caption', name: 'caption', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {label: "Location", name: "location", widget: "map", type: "Polygon", required: false }
      - name: 'bibliography'
        label: 'Annotated Bibliography'
        file: 'content/bibliography.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Featured Image', name: 'image', widget: 'image' }
          - { label: 'Image Caption', name: 'caption', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
